apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-v1
  namespace: demo-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api-v1
  template:
    metadata:
      labels:
        app: demo-api-v1
        tags.datadoghq.com/service: "demo-api"
        tags.datadoghq.com/env: "prod"
        tags.datadoghq.com/version: "1.0.0"
      annotations:
        ad.datadoghq.com/demo-api.logs: '[{"source": "python", "service": "demo-api"}]'
    spec:
      containers:
        - name: demo-api
          image: demo-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: demo-api-config-v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-v2
  namespace: demo-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api-v2
  template:
    metadata:
      labels:
        app: demo-api-v2
        tags.datadoghq.com/service: "demo-api"
        tags.datadoghq.com/env: "prod"
        tags.datadoghq.com/version: "2.0.0"
      annotations:
        ad.datadoghq.com/demo-api.logs: '[{"source": "python", "service": "demo-api"}]'
    spec:
      containers:
        - name: demo-api
          image: demo-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: demo-api-config-v2
